import { makeStyles } from "@material-ui/core";
import mq from "../../config/mq";
import backgroundImage from "../../assets/images/cerro.jpg";

export const useStyles = makeStyles((theme) => ({
  containerStyle: {
    position: "absolute",
    backgroundImage: `url(${backgroundImage})`,
    top: 0,
    left: 0,
    width: "100%",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    height: "19.5rem",
    filter: "blur(2px)",
    zIndex: 0,
    [mq("md")]: {
      height: "34.5rem",
      flexDirection: "row",
    },
  },
  backgroundImage: {
    overflowX: "hidden",
    overflowY: "hidden",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "3rem",
    height: "18rem",
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, .2)",
    borderBottom: ".8rem solid #FF4500",
    zIndex: 1,
    [mq("md")]: {
      height: "33rem",
    },
  },
  shadow: {
    marginTop: "4rem",
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    gap: ".5rem",
    zIndex: 1,
    "& h4": {
      fontSize: "1rem",
      color: "#fff",
      textAlign: "center",
      fontWeight: "bold",
      textTransform: "capitalize",
      textShadow: "4px 4px 6px rgba(0, 0, 0, 0.7)",
    },
    [mq("md")]: {
      gap: "3rem",
      marginTop: "3rem",
      "& h4": {
        fontSize: "1.5rem",
      },
    },
  },
  containerTitle: {
    zIndex: 1,
    margin: "2.5rem 0 0 3rem",
    "& h4": {
      fontWeight: "bold",
      textAlign: "center",
      fontSize: "2rem",
      textShadow: "2px 2px 4px rgba(0, 0, 0, 0.5)",
      textTransform: "capitalize",
    },
    [mq("md")]: {
      margin: "1.5rem 0 0 3rem",
      "& h4": {
        fontSize: "3rem",
      },
    },
  },
  title: {
    fontWeight: "bold",
    textAlign: "center",
    fontSize: "3rem",
    textShadow: "2px 2px 4px rgba(0, 0, 0, 0.5)",
    textTransform: "capitalize",
  },
  titleHighlight: {
    color: "#FF4500",
    textShadow: "2px 2px 4px rgba(0, 0, 0, 0.7)",
  },
  imageContainer: {
    display: "flex",
    alignItems: "center",
  },
  imageCard: {
    width: "6rem",
    height: "8rem",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    borderRadius: ".5rem",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "-10rem",
    position: "relative",
    [mq("md")]: {
      width: "14rem",
      height: "17rem",
    },
  },
  iconContainer: {
    width: "30px",
    height: "30px",
    borderRadius: "30px",
    bottom: 0,
    position: "absolute",
    display: "none",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: "-1.5rem",
    backgroundColor: "#fff",
    [mq("md")]: {
      width: "70px",
      height: "70px",
      borderRadius: "70px",
      display: "flex",
    },
  },
  iconImage: {
    width: "25px",
    height: "25px",
    borderRadius: "25px",
    [mq("md")]: {
      width: "65px",
      height: "65px",
      borderRadius: "65px",
    },
  },
  iconImageLarge: {
    width: "90px",
    height: "90px",
    borderRadius: "100%",
  },
}));
